MAP_MAPPING = {
  [0] = {"Submaps", "Cities", "Pallet Town", "Town"},    --Pallet Town
  [1] = {"Submaps", "Cities", "Viridian City", "City"},    --Viridian City
  [2] = {"Submaps", "Cities", "Pewter City", "City"},    --Pewter City
  [3] = {"Submaps", "Cities", "Cerulean City", "City"},    --Cerulean City
  [4] = {"Submaps", "Cities", "Lavender Town", "Town"},    --Lavender Town
  [5] = {"Submaps", "Cities", "Vermilion City", "City"},    --Vermilion City
  [6] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon City
  [7] = {"Submaps", "Cities", "Fuchsia City", "City"},    --Fuchsia City
  [8] = {"Submaps", "Cities", "Cinnabar Island", "Island"},    --Cinnabar Island
  [9] = {"Submaps", "Cities", "Indigo Plateau"},    --Pokémon League
  [10] = {"Submaps", "Cities", "Saffron City", "City"},    --Saffron City
  [12] = {"Submaps", "Routes", "Route 1"},    --Route 1
  [13] = {"Submaps", "Routes", "Route 2"},    --Route 2
  [14] = {"Submaps", "Routes", "Route 3"},    --Route 3
  [15] = {"Submaps", "Routes", "Route 4"},    --Route 4
  [16] = {"Submaps", "Routes", "Route 5"},    --Route 5
  [17] = {"Submaps", "Routes", "Route 6"},    --Route 6
  [18] = {"Submaps", "Routes", "Route 7"},    --Route 7
  [19] = {"Submaps", "Routes", "Route 8"},    --Route 8
  [20] = {"Submaps", "Routes", "Route 9"},    --Route 9
  [21] = {"Submaps", "Routes", "Route 10"},    --Route 10
  [22] = {"Submaps", "Routes", "Route 11"},    --Route 11
  [23] = {"Submaps", "Routes", "Route 12"},    --Route 12
  [24] = {"Submaps", "Routes", "Route 13"},    --Route 13
  [25] = {"Submaps", "Routes", "Route 14"},    --Route 14
  [26] = {"Submaps", "Routes", "Route 15"},    --Route 15
  [27] = {"Submaps", "Routes", "Route 16"},    --Route 16
  [28] = {"Submaps", "Routes", "Route 17"},    --Route 17
  [29] = {"Submaps", "Routes", "Route 18"},    --Route 18
  [30] = {"Submaps", "Routes", "Route 19"},    --Route 19
  [31] = {"Submaps", "Routes", "Route 20"},    --Route 20
  [32] = {"Submaps", "Routes", "Route 21"},    --Route 21
  [33] = {"Submaps", "Routes", "Route 22"},    --Route 22
  [34] = {"Submaps", "Routes", "Route 23"},    --Route 23
  [35] = {"Submaps", "Routes", "Route 24"},    --Route 24
  [36] = {"Submaps", "Routes", "Route 25"},    --Route 25
  [37] = {"Submaps", "Cities", "Pallet Town"},    --Red's house (first floor)
  [38] = {"Submaps", "Cities", "Pallet Town"},    --Red's house (second floor)
  [39] = {"Submaps", "Cities", "Pallet Town"},    --Blue's house
  [40] = {"Submaps", "Cities", "Pallet Town"},    --Professor Oak's Lab
  [41] = {"Submaps", "Cities", "Viridian City", "City"},    --Pokémon Center (Viridian City)
  [42] = {"Submaps", "Cities", "Viridian City", "City"},    --Poké Mart (Viridian City)
  [43] = {"Submaps", "Cities", "Viridian City", "City"},    --School (Viridian City)
  [44] = {"Submaps", "Cities", "Viridian City", "City"},    --House 1 (Viridian City)
  [45] = {"Submaps", "Cities", "Viridian City", "Gym"},    --Gym (Viridian City)
  [46] = {"Submaps", "Duneons", "Diglett's Cave"},    --Diglett's Cave (Route 2 entrance)
  [47] = {"Submaps", "Routes", "Route 2"},    --Gate (Viridian City/Pewter City) (Route 2)
  [48] = {"Submaps", "Routes", "Route 2"},    --Oak's Aide House 1 (Route 2)
  [49] = {"Submaps", "Dungeons", "Viridian Forest"},    --Gate (Route 2)
  [50] = {"Submaps", "Dungeons", "Viridian Forest"},    --Gate (Route 2/Viridian Forest) (Route 2)
  [51] = {"Submaps", "Dungeons", "Viridian Forest"},    --Viridian Forest
  [52] = {"Submaps", "Cities", "Pewter City", "City"},    --Pewter Museum (floor 1)
  [53] = {"Submaps", "Cities", "Pewter City", "City"},    --Pewter Museum (floor 2)
  [54] = {"Submaps", "Cities", "Pewter City", "Gym"},    --Gym (Pewter City)
  [55] = {"Submaps", "Cities", "Pewter City", "City"},    --House with disobedient Nidoran♂ (Pewter City)
  [56] = {"Submaps", "Cities", "Pewter City", "City"},    --Poké Mart (Pewter City)
  [57] = {"Submaps", "Cities", "Pewter City", "City"},    --House with two Trainers (Pewter City)
  [58] = {"Submaps", "Cities", "Pewter City", "City"},    --Pokémon Center (Pewter City)
  [59] = {"Submaps", "Dungeons", "Mt. Moon", "1F"},    --Mt. Moon (Route 3 entrance)
  [60] = {"Submaps", "Dungeons", "Mt. Moon", "B1F"},    --Mt. Moon
  [61] = {"Submaps", "Dungeons", "Mt. Moon", "B2F"},    --Mt. Moon
  [62] = {"Submaps", "Cities", "Cerulean City", "City"},    --Invaded house (Cerulean City)
  [63] = {"Submaps", "Cities", "Cerulean City", "City"},    --Poliwhirl for Jynx trade house
  [64] = {"Submaps", "Cities", "Cerulean City", "City"},    --Pokémon Center (Cerulean City)
  [65] = {"Submaps", "Cities", "Cerulean City", "Gym"},    --Gym (Cerulean City)
  [66] = {"Submaps", "Cities", "Cerulean City", "City"},    --Bike Shop (Cerulean City)
  [67] = {"Submaps", "Cities", "Cerulean City", "City"},    --Poké Mart (Cerulean City)
  [68] = {"Submaps", "Routes", "Route 4"},    --Pokémon Center (Route 4)
  [69] = {"Submaps", "Cities", "Cerulean City", "City"},    --Invaded house - alternative music (Cerulean City)
  [70] = {"Submaps", "Cities", "Saffron City", "City"},    --Saffron City Gate (Route 5)
  [71] = {"Submaps", "Dungeons", "Underground", "North-South"},    --Entrance to Underground Path (Route 5)
  [72] = {"Submaps", "Routes", "Route 5"},    --Daycare Center (Route 5)
  [73] = {"Submaps", "Cities", "Saffron City", "City"},    --Saffron City Gate (Route 6)
  [74] = {"Submaps", "Dungeons", "Underground", "North-South"},    --Entrance to Underground Path (Route 6)
  [75] = {"Submaps", "Dungeons", "Underground", "North-South"},    --Entrance to Underground Path (alternative music) (Route 6)
  [76] = {"Submaps", "Cities", "Saffron City", "City"},    --Saffron City Gate (Route 7)
  [77] = {"Submaps", "Dungeons", "Underground", "West-East"},    --Entrance to Underground Path (Route 7)
  [79] = {"Submaps", "Cities", "Saffron City", "City"},    --Saffron City Gate (Route 8)
  [80] = {"Submaps", "Dungeons", "Underground", "West-East"},    --Entrance to Underground Path (Route 8)
  [81] = {"Submaps", "Routes", "Route 10"},    --Pokémon Center (Rock Tunnel)
  [82] = {"Submaps", "Dungeons", "Rock Tunnel", "1F"},    --Rock Tunnel
  [83] = {"Submaps", "Dungeons", "Power Plant"},    --Power Plant
  [84] = {"Submaps", "Routes", "Route 11"},    --Gate 1F (Route 11-Route 12)
  [85] = {"Submaps", "Dungeons", "Diglett's Cave"},    --Diglett's Cave (Vermilion City entrance)
  [86] = {"Submaps", "Routes", "Route 11"},    --Gate 2F (Route 11-Route 12)
  [87] = {"Submaps", "Routes", "Route 12"},    --Gate (Route 12-Route 13)
  [88] = {"Submaps", "Routes", "Route 25"},    --Sea Cottage
  [89] = {"Submaps", "Cities", "Vermilion City", "City"},    --Pokémon Center (Vermilion City)
  [90] = {"Submaps", "Cities", "Vermilion City", "City"},    --Pokémon Fan Club (Vermilion City)
  [91] = {"Submaps", "Cities", "Vermilion City", "City"},    --Poké Mart (Vermilion City)
  [92] = {"Submaps", "Cities", "Vermilion City", "Gym"},    --Gym (Vermilion City)
  [93] = {"Submaps", "Cities", "Vermilion City", "City"},    --House with Pidgey (Vermilion City)
  [94] = {"Submaps", "Cities", "Vermilion City", "City"},    --Vermilion Harbor (Vermilion City)
  [95] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "1F"},    --S.S. Anne 1F
  [96] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "2F"},    --S.S. Anne 2F
  [97] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "3F"},    --S.S. Anne 3F
  [98] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "B1F"},    --S.S. Anne B1F
  [99] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "Deck"},    --S.S. Anne (Deck)
  [100] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "Kitchen"},    --S.S. Anne (Kitchen)
  [101] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "Captain's Room"},    --S.S. Anne (Captain's room)
  [102] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "1F"},    --S.S. Anne 1F (Gentleman's room)
  [103] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "2F"},    --S.S. Anne 2F (Gentleman's room)
  [104] = {"Submaps", "Cities", "Vermilion City", "S.S. Anne", "B1F"},    --S.S. Anne B1F (Sailor/Fisherman's room)
  [108] = {"Submaps", "Dungeons", "Victory Road", "1F"},    --Victory Road (Route 23 entrance)
  [113] = {"Submaps", "Cities", "Indigo Plateau"},    --Lance's Elite Four room
  [118] = {"Submaps", "Cities", "Indigo Plateau"},    --Hall of Fame
  [119] = {"Submaps", "Dungeons", "Underground", "North-South"},    --Underground Path (Route 5-Route 6)
  [120] = {"Submaps", "Cities", "Indigo Plateau"},    --Blue (Champion)'s room
  [121] = {"Submaps", "Dungeons", "Underground", "West-East"},    --Underground Path (Route 7-Route 8)
  [122] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Department Store 1F
  [123] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Department Store 2F
  [124] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Department Store 3F
  [125] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Department Store 4F
  [126] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Department Store Rooftop Square
  [127] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Department Store Lift
  [128] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Mansion 1F
  [129] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Mansion 2F
  [130] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Mansion 3F
  [131] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Mansion 4F
  [132] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Mansion 4F (Eevee building)
  [133] = {"Submaps", "Cities", "Celadon City", "City"},    --Pokémon Center (Celadon City)
  [134] = {"Submaps", "Cities", "Celadon City", "City"},    --Gym (Celadon City)
  [135] = {"Submaps", "Cities", "Celadon City", "Game Corner"},    --Rocket Game Corner (Celadon City)
  [136] = {"Submaps", "Cities", "Celadon City", "City"},    --Celadon Department Store 5F
  [137] = {"Submaps", "Cities", "Celadon City", "City"},    --Prize corner (Celadon City)
  [138] = {"Submaps", "Cities", "Celadon City", "City"},    --Restaurant (Celadon City)
  [139] = {"Submaps", "Cities", "Celadon City", "City"},    --House with Team Rocket members (Celadon City)
  [140] = {"Submaps", "Cities", "Celadon City", "City"},    --Hotel (Celadon City)
  [141] = {"Submaps", "Cities", "Lavender Town", "Town"},    --Pokémon Center (Lavender Town)
  [142] = {"Submaps", "Cities", "Lavender Town", "Pokémon Tower", "1F"},    --Pokémon Tower 1F
  [143] = {"Submaps", "Cities", "Lavender Town", "Pokémon Tower", "2F"},    --Pokémon Tower 2F
  [144] = {"Submaps", "Cities", "Lavender Town", "Pokémon Tower", "3F"},    --Pokémon Tower 3F
  [145] = {"Submaps", "Cities", "Lavender Town", "Pokémon Tower", "4F"},    --Pokémon Tower 4F
  [146] = {"Submaps", "Cities", "Lavender Town", "Pokémon Tower", "5F"},    --Pokémon Tower 5F
  [147] = {"Submaps", "Cities", "Lavender Town", "Pokémon Tower", "6F"},    --Pokémon Tower 6F
  [148] = {"Submaps", "Cities", "Lavender Town", "Pokémon Tower", "7F"},    --Pokémon Tower 7F
  [149] = {"Submaps", "Cities", "Lavender Town", "Town"},    --Mr. Fuji's house (Lavender Town)
  [150] = {"Submaps", "Cities", "Lavender Town", "Town"},    --Poké Mart (Lavender Town)
  [151] = {"Submaps", "Cities", "Lavender Town", "Town"},    --House with NPC discussing Cubone's mother
  [152] = {"Submaps", "Cities", "Fuchsia City", "City"},    --Poké Mart (Fuchsia City)
  [153] = {"Submaps", "Cities", "Fuchsia City", "City"},    --House with NPCs discussing Bill (Fuchsia City)
  [154] = {"Submaps", "Cities", "Fuchsia City", "City"},    --Pokémon Center (Fuchsia City)
  [155] = {"Submaps", "Cities", "Fuchsia City", "City"},    --Warden's house (Fuchsia City)
  [156] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "Center"},    --Safari Zone gate (Fuchsia City)
  [157] = {"Submaps", "Cities", "Fuchsia City", "Gym"},    --Gym (Fuchsia City)
  [158] = {"Submaps", "Cities", "Fuchsia City", "City"},    --House with NPCs discussing Baoba (Fuchsia City)
  [159] = {"Submaps", "Dungeons", "Seafoam Islands", "B1F"},    --Seafoam Islands
  [160] = {"Submaps", "Dungeons", "Seafoam Islands", "B3F"},    --Seafoam Islands
  [161] = {"Submaps", "Dungeons", "Seafoam Islands", "B2F"},    --Seafoam Islands
  [162] = {"Submaps", "Dungeons", "Seafoam Islands", "B4F"},    --Seafoam Islands
  [163] = {"Submaps", "Cities", "Vermilion City", "City"},    --Vermilion City Fishing Brother
  [164] = {"Submaps", "Cities", "Fuchsia City", "City"},    --Fuchsia City Fishing Brother
  [165] = {"Submaps", "Cities", "Cinnabar Island", "Pokémon Mansion", "1F"},    --Pokémon Mansion (1F)
  [166] = {"Submaps", "Cities", "Cinnabar Island", "Gym"},    --Gym (Cinnabar Island)
  [167] = {"Submaps", "Cities", "Cinnabar Island", "Lab", "Corridor"},    --Pokémon Lab (Cinnabar Island)
  [168] = {"Submaps", "Cities", "Cinnabar Island", "Lab", "Trade Room"},    --Pokémon Lab - Trade room (Cinnabar Island)
  [169] = {"Submaps", "Cities", "Cinnabar Island", "Lab", "Metronome Room"},    --Pokémon Lab - Room with scientists (Cinnabar Island)
  [170] = {"Submaps", "Cities", "Cinnabar Island", "Lab", "Fossil Room"},    --Pokémon Lab - Fossil resurrection room (Cinnabar Island)
  [171] = {"Submaps", "Cities", "Cinnabar Island", "City"},    --Pokémon Center (Cinnabar Island)
  [172] = {"Submaps", "Cities", "Cinnabar Island", "City"},    --Poké Mart (Cinnabar Island)
  [173] = {"Submaps", "Cities", "Cinnabar Island", "City"},    --Poké Mart - alternative music (Cinnabar Island)
  [174] = {"Submaps", "Cities", "Indigo Plateau"},    --Pokémon Center (Indigo Plateau)
  [175] = {"Submaps", "Cities", "Saffron City", "City"},    --Copycat's house 1F (Saffron City)
  [176] = {"Submaps", "Cities", "Saffron City", "City"},    --Copycat's house 2F (Saffron City)
  [177] = {"Submaps", "Cities", "Saffron City", "Dojo"},    --Fighting Dojo (Saffron City)
  [178] = {"Submaps", "Cities", "Saffron City", "Gym"},    --Gym (Saffron City)
  [179] = {"Submaps", "Cities", "Saffron City", "City"},    --House with Pidgey (Saffron City)
  [180] = {"Submaps", "Cities", "Saffron City", "City"},    --Poké Mart (Saffron City)
  [181] = {"Submaps", "Cities", "Saffron City", "Silph Co", "1F"},    --Silph Co. 1F
  [182] = {"Submaps", "Cities", "Saffron City", "City"},    --Pokémon Center (Saffron City)
  [183] = {"Submaps", "Cities", "Saffron City", "City"},    --Mr. Psychic's house (Saffron City)
  [184] = {"Submaps", "Routes", "Route 15"},    --Gate 1F (Route 15)
  [185] = {"Submaps", "Routes", "Route 15"},    --Gate 2F (Route 15)
  [186] = {"Submaps", "Routes", "Route 16"},    --Gate 1F (Cycling Road) (Route 16)
  [187] = {"Submaps", "Routes", "Route 16"},    --Gate 2F (Cycling Road) (Route 16)
  [188] = {"Submaps", "Routes", "Route 16"},    --Secret house (Cycling Road) (Route 16)
  [189] = {"Submaps", "Routes", "Route 12"},    --Route 12 Fishing Brother
  [190] = {"Submaps", "Routes", "Route 18"},    --Gate 1F (Route 18)
  [191] = {"Submaps", "Routes", "Route 18"},    --Gate 2F (Route 18)
  [192] = {"Submaps", "Dungeons", "Seafoam Islands", "1F"},    --Seafoam Islands
  [193] = {"Submaps", "Routes", "Route 22"},    --Badges check gate (Route 22)
  [194] = {"Submaps", "Dungeons", "Victory Road", "2F"},    --Victory Road
  [195] = {"Submaps", "Routes", "Route 12"},    --Gate 2F (Route 12)
  [196] = {"Submaps", "Cities", "Vermilion City", "City"},    --House with NPC and HM moves advice (Vermilion City)
  [197] = {"Submaps", "Dungeons", "Diglett's Cave"},    --Diglett's Cave
  [198] = {"Submaps", "Dungeons", "Victory Road", "3F"},    --Victory Road
  [199] = {"Submaps", "Cities", "Celadon City", "Rocket Hideout", "B1F"},    --Team Rocket Hideout (B1F)
  [200] = {"Submaps", "Cities", "Celadon City", "Rocket Hideout", "B2F"},    --Team Rocket Hideout (B2F)
  [201] = {"Submaps", "Cities", "Celadon City", "Rocket Hideout", "B3F"},    --Team Rocket Hideout (B3F)
  [202] = {"Submaps", "Cities", "Celadon City", "Rocket Hideout", "B4F"},    --Team Rocket Hideout (B4F)
  [203] = {},    --Team Rocket Hideout (Lift)
  [207] = {"Submaps", "Cities", "Saffron City", "Silph Co", "2F"},    --Silph Co. (2F)
  [208] = {"Submaps", "Cities", "Saffron City", "Silph Co", "3F"},    --Silph Co. (3F)
  [209] = {"Submaps", "Cities", "Saffron City", "Silph Co", "4F"},    --Silph Co. (4F)
  [210] = {"Submaps", "Cities", "Saffron City", "Silph Co", "5F"},    --Silph Co. (5F)
  [211] = {"Submaps", "Cities", "Saffron City", "Silph Co", "6F"},    --Silph Co. (6F)
  [212] = {"Submaps", "Cities", "Saffron City", "Silph Co", "7F"},    --Silph Co. (7F)
  [213] = {"Submaps", "Cities", "Saffron City", "Silph Co", "8F"},    --Silph Co. (8F)
  [214] = {"Submaps", "Cities", "Cinnabar Island", "Pokémon Mansion", "2F"},    --Pokémon Mansion (2F)
  [215] = {"Submaps", "Cities", "Cinnabar Island", "Pokémon Mansion", "3F"},    --Pokémon Mansion (3F)
  [216] = {"Submaps", "Cities", "Cinnabar Island", "Pokémon Mansion", "B1F"},    --Pokémon Mansion (B1F)
  [217] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "East"},    --Safari Zone (Area 1)
  [218] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "North"},    --Safari Zone (Area 2)
  [219] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "West"},    --Safari Zone (Area 3)
  [220] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "Center"},    --Safari Zone (Entrance)
  [221] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "Center"},    --Safari Zone (Rest house 1)
  [222] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "West"},    --Safari Zone (Prize house)
  [223] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "East"},    --Safari Zone (Rest house 2)
  [224] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "North"},    --Safari Zone (Rest house 3)
  [225] = {"Submaps", "Cities", "Fuchsia City", "Safari Zone", "West"},    --Safari Zone (Rest house 4)
  [226] = {"Submaps", "Cities", "Cerulean City", "Cave", "2F"},    --Cerulean Cave
  [227] = {"Submaps", "Cities", "Cerulean City", "Cave", "1F"},    --Cerulean Cave 1F
  [228] = {"Submaps", "Cities", "Cerulean City", "Cave", "B1F"},    --Cerulean Cave B1F
  [229] = {"Submaps", "Cities", "Lavender Town", "Town"},    --Name Rater's house (Lavender Town)
  [230] = {"Submaps", "Cities", "Cerulean City", "City"},    --Cerulean City (Gym Badge man)
  [232] = {"Submaps", "Dungeons", "Rock Tunnel", "2F"},    --Rock Tunnel
  [233] = {"Submaps", "Cities", "Saffron City", "Silph Co", "9F"},    --Silph Co. 9F
  [234] = {"Submaps", "Cities", "Saffron City", "Silph Co", "10F"},    --Silph Co. 10F
  [235] = {"Submaps", "Cities", "Saffron City", "Silph Co", "11F"},    --Silph Co. 11F
  [236] = {},    --Silph Co. Lift
  [245] = {"Submaps", "Cities", "Indigo Plateau"},    --Lorelei's room
  [246] = {"Submaps", "Cities", "Indigo Plateau"},    --Bruno's room
  [247] = {"Submaps", "Cities", "Indigo Plateau"}     --Agatha's room
}